name: Dungeon
version: '${project.version}'
main: com.extremecounting.dungeon.Dungeon
api-version: 1.20
authors: [ extremecounting ]
description: Plugin for making RPG
commands:
  day:
    description: makes it day
    usage: /<command>
  lightningrod:
    description: gives a lightning rod
    usage: /<command>
  bandit:
    description: summons a bandit
    usage: /<command>
  spear:
    description: gives a primitive spear
    usage: /<command>
  givestuff:
    description: gives stuff
    usage: /<command>
  island:
    description: island commands
    usage: /<command> <arg>
    aliases:
      - is
  test1:
    description: test command
    usage: /<command>
  createspawner:
    description: creates a spawner
    usage: /<command> <arg> <arg> <arg> <arg> <arg>
  spawnertest:
    description: tests the config files for spawner
    usage: /<commmand>
  spawner:
    description: spawner info
    usage: /<command> <arg> <arg>
  suicide:
    description: commits suicide
    usage: /<command>
  spawncamel123:
    description: summons camel
    usage: /<command>
  cleane:
    description: kills entities
    usage: /<command>
  createtin:
    description: creates tin item
    usage: /<command>
  spawnerstart:
    description: starts all spawners
    usage: /<command>
  spawnfarmer:
    description: spawns a farmer npc
    usage: /<command>
  spawnmayor:
    description: spawner a mayor npc
    usage: /<command>
  givecoinbag:
    description: gives the player a coin bag
    usage: /<command>
  tpa:
    description: Request teleportation to another user
    usage: /<command> <arg>
  tpaccept:
    description: Accept teleportation request
    usage: /<command> <arg>
  tpdeny:
    description: Deny teleportation request
    usage: /<command> <arg>
  giverapture:
    description: gives all rapture books
    usage: /<command>
  givepoisons:
    description: gives all poison books
    usage: /<command>
  givescavenger:
    description: gives all scavenger books
    usage: /<command>
